name: main
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout working-directory
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install depencies
        run: npm ci

      - name: Start Lint
        run: make lint
        
      - name: Start test 
        run: make test 
        
      - name: SonarQube 
        uses: SonarSource/sonarqube-scan-action@<action version or sha1>
        with:
          scannerVersion: 6.2.0.4584
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
