name: main
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout working-directory
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install depencies
        run: npm ci

      - name: Start Lint
        run: make lint

      - name: Make Coverage
        run: make coverage
        
      - name: SonarCloud Scan 
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=mammoth90_frontend-project-46
            -Dsonar.organization=mammoth90
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
