name: main
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout working-directory
        uses: action/checkout@v4

      - name: Setup Node.js
        uses: action/setup-node@v4
        with:
          node-version: 20

      - name: Install depencies
        run: npm ci

      - name: Start Lint
        run: make lint
        
      - name: Start test 
        run: make test 
        
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

        
      
  
